---
- hosts: all
  sudo: true
  vars:
    document_root: /vagrant
  tasks:
  - name: Update apt cache "apt-get update"
    apt: update_cache=yes
  - include: tasks/apache.yml
  - include: tasks/mysql.yml
  - include: tasks/java.yml
  - include: tasks/php.yml
