---
- hosts: all
  sudo: true
  vars:
    document_root: /vagrant
  handlers:
  - name: reload apache
    service: name=apache2 state=reloaded
  pre_tasks:
  - name: Update apt cache "apt-get update"
    apt: update_cache=yes
  roles:
  - webserver
  - database
